# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  this_month_payment_remainder:
    class: "ThisMonthPaymentReminderJob"
    schedule: "* * * * *"
  next_payment_update:
    class: "NextPaymentUpdateJob"
    schedule: "* * * * *"
  get_exchange_data:
    class: "GetExchangeDataJob"
    schedule: "* * * * *"

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  this_month_payment_remainder:
    class: "ThisMonthPaymentReminderJob"
    schedule: 0 9 1 * * # begining of the month at 9 am
  next_payment_update:
    class: "NextPaymentUpdateJob"
    schedule: every day at 0am
  get_exchange_data:
    class: "GetExchangeDataJob"
    schedule: every day at 0am
